/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UrlService } from "../url.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UrlCreateInput } from "./UrlCreateInput";
import { UrlWhereInput } from "./UrlWhereInput";
import { UrlWhereUniqueInput } from "./UrlWhereUniqueInput";
import { UrlFindManyArgs } from "./UrlFindManyArgs";
import { UrlUpdateInput } from "./UrlUpdateInput";
import { Url } from "./Url";
import { UrlGroupFindManyArgs } from "../../urlGroup/base/UrlGroupFindManyArgs";
import { UrlGroup } from "../../urlGroup/base/UrlGroup";
import { UrlGroupWhereUniqueInput } from "../../urlGroup/base/UrlGroupWhereUniqueInput";
import { UserFindManyArgs } from "../../user/base/UserFindManyArgs";
import { User } from "../../user/base/User";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class UrlControllerBase {
  constructor(
    protected readonly service: UrlService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Url",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Url })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: UrlCreateInput): Promise<Url> {
    return await this.service.create({
      data: data,
      select: {
        address: true,
        createdAt: true,
        description: true,
        favico: true,
        hits: true,
        id: true,
        name: true,
        owner: true,
        shortAddress: true,
        tags: true,
        thumbnail: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Url",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Url] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(UrlFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Url[]> {
    const args = plainToClass(UrlFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        address: true,
        createdAt: true,
        description: true,
        favico: true,
        hits: true,
        id: true,
        name: true,
        owner: true,
        shortAddress: true,
        tags: true,
        thumbnail: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Url",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Url })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: UrlWhereUniqueInput
  ): Promise<Url | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        address: true,
        createdAt: true,
        description: true,
        favico: true,
        hits: true,
        id: true,
        name: true,
        owner: true,
        shortAddress: true,
        tags: true,
        thumbnail: true,
        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Url",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Url })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: UrlWhereUniqueInput,
    @common.Body() data: UrlUpdateInput
  ): Promise<Url | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          address: true,
          createdAt: true,
          description: true,
          favico: true,
          hits: true,
          id: true,
          name: true,
          owner: true,
          shortAddress: true,
          tags: true,
          thumbnail: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Url",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Url })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: UrlWhereUniqueInput
  ): Promise<Url | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          address: true,
          createdAt: true,
          description: true,
          favico: true,
          hits: true,
          id: true,
          name: true,
          owner: true,
          shortAddress: true,
          tags: true,
          thumbnail: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "UrlGroup",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/urlGroups")
  @ApiNestedQuery(UrlGroupFindManyArgs)
  async findManyUrlGroups(
    @common.Req() request: Request,
    @common.Param() params: UrlWhereUniqueInput
  ): Promise<UrlGroup[]> {
    const query = plainToClass(UrlGroupFindManyArgs, request.query);
    const results = await this.service.findUrlGroups(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        topic: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Url",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/urlGroups")
  async connectUrlGroups(
    @common.Param() params: UrlWhereUniqueInput,
    @common.Body() body: UrlGroupWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      urlGroups: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Url",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/urlGroups")
  async updateUrlGroups(
    @common.Param() params: UrlWhereUniqueInput,
    @common.Body() body: UrlGroupWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      urlGroups: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Url",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/urlGroups")
  async disconnectUrlGroups(
    @common.Param() params: UrlWhereUniqueInput,
    @common.Body() body: UrlGroupWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      urlGroups: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/users")
  @ApiNestedQuery(UserFindManyArgs)
  async findManyUsers(
    @common.Req() request: Request,
    @common.Param() params: UrlWhereUniqueInput
  ): Promise<User[]> {
    const query = plainToClass(UserFindManyArgs, request.query);
    const results = await this.service.findUsers(params.id, {
      ...query,
      select: {
        createdAt: true,
        firstName: true,
        id: true,
        lastName: true,
        role: true,
        roles: true,
        updatedAt: true,
        username: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Url",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/users")
  async connectUsers(
    @common.Param() params: UrlWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Url",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/users")
  async updateUsers(
    @common.Param() params: UrlWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Url",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/users")
  async disconnectUsers(
    @common.Param() params: UrlWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
