/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UrlGroupService } from "../urlGroup.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UrlGroupCreateInput } from "./UrlGroupCreateInput";
import { UrlGroupWhereInput } from "./UrlGroupWhereInput";
import { UrlGroupWhereUniqueInput } from "./UrlGroupWhereUniqueInput";
import { UrlGroupFindManyArgs } from "./UrlGroupFindManyArgs";
import { UrlGroupUpdateInput } from "./UrlGroupUpdateInput";
import { UrlGroup } from "./UrlGroup";
import { UrlFindManyArgs } from "../../url/base/UrlFindManyArgs";
import { Url } from "../../url/base/Url";
import { UrlWhereUniqueInput } from "../../url/base/UrlWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class UrlGroupControllerBase {
  constructor(
    protected readonly service: UrlGroupService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "UrlGroup",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: UrlGroup })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: UrlGroupCreateInput): Promise<UrlGroup> {
    return await this.service.create({
      data: data,
      select: {
        createdAt: true,
        id: true,
        topic: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "UrlGroup",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [UrlGroup] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(UrlGroupFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<UrlGroup[]> {
    const args = plainToClass(UrlGroupFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,
        topic: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "UrlGroup",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: UrlGroup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: UrlGroupWhereUniqueInput
  ): Promise<UrlGroup | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,
        topic: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "UrlGroup",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: UrlGroup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: UrlGroupWhereUniqueInput,
    @common.Body() data: UrlGroupUpdateInput
  ): Promise<UrlGroup | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          topic: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "UrlGroup",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: UrlGroup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: UrlGroupWhereUniqueInput
  ): Promise<UrlGroup | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,
          topic: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Url",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/topicItems")
  @ApiNestedQuery(UrlFindManyArgs)
  async findManyTopicItems(
    @common.Req() request: Request,
    @common.Param() params: UrlGroupWhereUniqueInput
  ): Promise<Url[]> {
    const query = plainToClass(UrlFindManyArgs, request.query);
    const results = await this.service.findTopicItems(params.id, {
      ...query,
      select: {
        address: true,
        createdAt: true,
        description: true,
        favico: true,
        hits: true,
        id: true,
        name: true,
        owner: true,
        shortAddress: true,
        tags: true,
        thumbnail: true,
        title: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "UrlGroup",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/topicItems")
  async connectTopicItems(
    @common.Param() params: UrlGroupWhereUniqueInput,
    @common.Body() body: UrlWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      topicItems: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "UrlGroup",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/topicItems")
  async updateTopicItems(
    @common.Param() params: UrlGroupWhereUniqueInput,
    @common.Body() body: UrlWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      topicItems: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "UrlGroup",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/topicItems")
  async disconnectTopicItems(
    @common.Param() params: UrlGroupWhereUniqueInput,
    @common.Body() body: UrlWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      topicItems: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
